"""FocusFlow theme — light and dark palettes."""

APP_NAME = "FocusFlow"
APP_SUBTITLE = "Deep Work Tracker"

FONT = "Inter"
FONT_FALLBACK = "Segoe UI"
FONT_MONO = "Consolas"

DEFAULT_WEEKLY_GOAL_HOURS = 10
DEFAULT_INACTIVITY_MINUTES = 10

DAY_NAMES_ES = [
    "Lunes",
    "Martes",
    "Miércoles",
    "Jueves",
    "Viernes",
    "Sábado",
    "Domingo",
]
MONTH_NAMES_ES = [
    "ene",
    "feb",
    "mar",
    "abr",
    "may",
    "jun",
    "jul",
    "ago",
    "sep",
    "oct",
    "nov",
    "dic",
]

HEAT_CELL_GAP = 4
HEAT_CELL_MIN = 16
HEAT_CELL_MAX = 22
HEAT_CELL_RADIUS = 4
HEAT_MONTH_GAP = 32
HEAT_CARD_PAD = 20

_LIGHT = {
    "PRIMARY": "#FF6B6B",
    "PRIMARY_HOVER": "#E85555",
    "SECONDARY": "#7EC8A4",
    "SECONDARY_HOVER": "#6BB892",
    "TERTIARY": "#C3B1E1",
    "TERTIARY_HOVER": "#B09FD4",
    "TERTIARY_DARK": "#6B5B95",
    "BG": "#F7F5F2",
    "NEUTRAL": "#F7F5F2",
    "SIDEBAR": "#EDEAE4",
    "CARD": "#FFFFFF",
    "CARD_BORDER": "#EEEBE6",
    "CARD_SHADOW": "#E3E0DB",
    "INPUT": "#F2F0EB",
    "NAV_ACTIVE": "#E8E4F8",
    "NAV_ACTIVE_TEXT": "#6B5B95",
    "SESSIONS_BG": "#F0EDE8",
    "ACCORDION_ROW": "#F2F0EB",
    "BTN_DISABLED_BG": "#F5F3F0",
    "BTN_DISABLED_BORDER": "#D9D5CF",
    "BTN_DISABLED_TEXT": "#A8A4A0",
    "HEAT_EMPTY": "#E8E2DA",
    "HEAT_LOW": "#D4BBEE",
    "HEAT_MED": "#A97DD4",
    "HEAT_HIGH": "#6C3FA8",
    "HEAT_GAP": "#F7F5F2",
    "HEAT_LABEL": "#6B6560",
    "HEAT_CARD_SHADOW": "#E0DBD4",
    "ACCORDION_CORAL": "#FFE8E8",
    "ACCORDION_CORAL_ACTIVE": "#FFD4D4",
    "ACCORDION_SAGE": "#E4F5EC",
    "ACCORDION_SAGE_ACTIVE": "#CFEADB",
    "SUCCESS_BG": "#D4EDDA",
    "SUCCESS": "#155724",
    "SUCCESS_HOVER": "#BFE8C9",
    "PAUSE_BG": "#FFF3CD",
    "PAUSE_TEXT": "#856404",
    "DANGER": "#FF6B6B",
    "DANGER_HOVER": "#E85555",
    "WARNING": "#E8A838",
    "TEXT": "#2D2D2D",
    "TEXT_MUTED": "#777777",
    "TEXT_DIM": "#999999",
    "TEXT_ON_PRIMARY": "#FFFFFF",
    "CHART_BAR": "#C3B1E1",
    "CHART_BAR_TODAY": "#6B5B95",
    "CHART_EMPTY": "#EEEBE6",
}

_DARK = {
    "PRIMARY": "#10E881",
    "PRIMARY_HOVER": "#0CCF6E",
    "SECONDARY": "#8850F0",
    "SECONDARY_HOVER": "#7040D8",
    "TERTIARY": "#FA3F9F",
    "TERTIARY_HOVER": "#E0358E",
    "TERTIARY_DARK": "#FFFFFF",
    "BG": "#1a1a2e",
    "NEUTRAL": "#2F0975",
    "SIDEBAR": "#16162a",
    "CARD": "#22223a",
    "CARD_BORDER": "#343452",
    "CARD_SHADOW": "#0c0c18",
    "INPUT": "#2a2a45",
    "NAV_ACTIVE": "#8850F0",
    "NAV_ACTIVE_TEXT": "#F0F0F0",
    "SESSIONS_BG": "#22223a",
    "ACCORDION_ROW": "#2a2a45",
    "BTN_DISABLED_BG": "#2a2a42",
    "BTN_DISABLED_BORDER": "#3a3a55",
    "BTN_DISABLED_TEXT": "#F0F0F0",
    "HEAT_EMPTY": "#2F0975",
    "HEAT_LOW": "#1B6B52",
    "HEAT_MED": "#0F9A6A",
    "HEAT_HIGH": "#10E881",
    "HEAT_GAP": "#1a1a2e",
    "HEAT_LABEL": "#F0F0F0",
    "HEAT_CARD_SHADOW": "#0c0c18",
    "ACCORDION_CORAL": "#3a1a32",
    "ACCORDION_CORAL_ACTIVE": "#4d2340",
    "ACCORDION_SAGE": "#261e3d",
    "ACCORDION_SAGE_ACTIVE": "#322850",
    "SUCCESS_BG": "#1a3d2e",
    "SUCCESS": "#F0F0F0",
    "SUCCESS_HOVER": "#0CCF6E",
    "PAUSE_BG": "#3d3520",
    "PAUSE_TEXT": "#F0F0F0",
    "DANGER": "#FA3F9F",
    "DANGER_HOVER": "#E0358E",
    "WARNING": "#E8A838",
    "TEXT": "#F0F0F0",
    "TEXT_MUTED": "#F0F0F0",
    "TEXT_DIM": "#F0F0F0",
    "TEXT_ON_PRIMARY": "#F0F0F0",
    "CHART_BAR": "#8850F0",
    "CHART_BAR_TODAY": "#7040D8",
    "CHART_EMPTY": "#343452",
}

_current_mode = "light"

# Module-level tokens (updated by apply_theme)
PRIMARY = _LIGHT["PRIMARY"]
PRIMARY_HOVER = _LIGHT["PRIMARY_HOVER"]
SECONDARY = _LIGHT["SECONDARY"]
SECONDARY_HOVER = _LIGHT["SECONDARY_HOVER"]
TERTIARY = _LIGHT["TERTIARY"]
TERTIARY_HOVER = _LIGHT["TERTIARY_HOVER"]
TERTIARY_DARK = _LIGHT["TERTIARY_DARK"]
BG = _LIGHT["BG"]
NEUTRAL = _LIGHT["NEUTRAL"]
SIDEBAR = _LIGHT["SIDEBAR"]
CARD = _LIGHT["CARD"]
CARD_BORDER = _LIGHT["CARD_BORDER"]
CARD_SHADOW = _LIGHT["CARD_SHADOW"]
INPUT = _LIGHT["INPUT"]
NAV_ACTIVE = _LIGHT["NAV_ACTIVE"]
NAV_ACTIVE_TEXT = _LIGHT["NAV_ACTIVE_TEXT"]
SESSIONS_BG = _LIGHT["SESSIONS_BG"]
ACCORDION_ROW = _LIGHT["ACCORDION_ROW"]
BTN_DISABLED_BG = _LIGHT["BTN_DISABLED_BG"]
BTN_DISABLED_BORDER = _LIGHT["BTN_DISABLED_BORDER"]
BTN_DISABLED_TEXT = _LIGHT["BTN_DISABLED_TEXT"]
HEAT_EMPTY = _LIGHT["HEAT_EMPTY"]
HEAT_LOW = _LIGHT["HEAT_LOW"]
HEAT_MED = _LIGHT["HEAT_MED"]
HEAT_HIGH = _LIGHT["HEAT_HIGH"]
HEAT_GAP = _LIGHT["HEAT_GAP"]
HEAT_LABEL = _LIGHT["HEAT_LABEL"]
HEAT_CARD_SHADOW = _LIGHT["HEAT_CARD_SHADOW"]
ACCORDION_CORAL = _LIGHT["ACCORDION_CORAL"]
ACCORDION_CORAL_ACTIVE = _LIGHT["ACCORDION_CORAL_ACTIVE"]
ACCORDION_SAGE = _LIGHT["ACCORDION_SAGE"]
ACCORDION_SAGE_ACTIVE = _LIGHT["ACCORDION_SAGE_ACTIVE"]
SUCCESS_BG = _LIGHT["SUCCESS_BG"]
SUCCESS = _LIGHT["SUCCESS"]
SUCCESS_HOVER = _LIGHT["SUCCESS_HOVER"]
PAUSE_BG = _LIGHT["PAUSE_BG"]
PAUSE_TEXT = _LIGHT["PAUSE_TEXT"]
DANGER = _LIGHT["DANGER"]
DANGER_HOVER = _LIGHT["DANGER_HOVER"]
WARNING = _LIGHT["WARNING"]
TEXT = _LIGHT["TEXT"]
TEXT_MUTED = _LIGHT["TEXT_MUTED"]
TEXT_DIM = _LIGHT["TEXT_DIM"]
TEXT_ON_PRIMARY = _LIGHT["TEXT_ON_PRIMARY"]
CHART_BAR = _LIGHT["CHART_BAR"]
CHART_BAR_TODAY = _LIGHT["CHART_BAR_TODAY"]
CHART_EMPTY = _LIGHT["CHART_EMPTY"]


def font(size: int, *, bold: bool = False, mono: bool = False) -> tuple:
    family = FONT_MONO if mono else FONT
    weight = "bold" if bold else "normal"
    return (family, size, weight) if bold else (family, size)


def is_dark() -> bool:
    return _current_mode == "dark"


def apply_theme(mode: str) -> None:
    global _current_mode
    global PRIMARY, PRIMARY_HOVER, SECONDARY, SECONDARY_HOVER
    global TERTIARY, TERTIARY_HOVER, TERTIARY_DARK
    global BG, NEUTRAL, SIDEBAR, CARD, CARD_BORDER, CARD_SHADOW, INPUT
    global NAV_ACTIVE, NAV_ACTIVE_TEXT, SESSIONS_BG, ACCORDION_ROW
    global BTN_DISABLED_BG, BTN_DISABLED_BORDER, BTN_DISABLED_TEXT
    global HEAT_EMPTY, HEAT_LOW, HEAT_MED, HEAT_HIGH, HEAT_GAP, HEAT_LABEL, HEAT_CARD_SHADOW
    global ACCORDION_CORAL, ACCORDION_CORAL_ACTIVE, ACCORDION_SAGE, ACCORDION_SAGE_ACTIVE
    global SUCCESS_BG, SUCCESS, SUCCESS_HOVER, PAUSE_BG, PAUSE_TEXT
    global DANGER, DANGER_HOVER, WARNING
    global TEXT, TEXT_MUTED, TEXT_DIM, TEXT_ON_PRIMARY
    global CHART_BAR, CHART_BAR_TODAY, CHART_EMPTY

    _current_mode = "dark" if mode == "dark" else "light"
    palette = _DARK if _current_mode == "dark" else _LIGHT

    for key, value in palette.items():
        globals()[key] = value
